export const COLORS = {
    choiceBlue: "#4389F8",
    choiceLightBlue: "rgba(67, 137, 248, 0.3)",
    choiceGreen: "#29C677",
    choiceLightGreen: "rgba(41, 198, 119, 0.3)",
    choicePurple: "#6A28E6",
    choiceLightPurple: "rgba(106,40,230,0.3)",
    choiceRed: "#E63146",
    choiceLightRed: "rgba(230,49,70,0.3)",
    choiceYellow: "#F7CF34",
    choiceLightYellow: "rgba(247, 207, 52, 0.3)",
    choiceAsh: "#B4B4C9",
    choiceLightAsh: "rgba(180, 180, 201, 0.3)"
};

export const DIFFICULTY_OPTIONS = [
    {
        key: "1",
        text: "Beginner",
        value: "Beginner"
    },
    {
        key: "2",
        text: "Intermediate",
        value: "Intermediate"
    },
    {
        key: "3",
        text: "Advanced",
        value: "Advanced"
    }
];

export const CATEGORY_OPTIONS = [
    {
        key: "1",
        text: "React",
        value: "React"
    },
    {
        key: "2",
        text: "Design",
        value: "Design"
    },
    {
        key: "3",
        text: "Backend",
        value: "Backend"
    }
];

export const TOPICS = [
    {
        key: "1",
        text: "English",
        value: "English"
    },
    {
        key: "2",
        text: "Maths",
        value: "Maths"
    },
    {
        key: "3",
        text: "Literature",
        value: "Literature"
    }
];

export const CATEGORIES = {
    "Art & Design": [
        "3D Design",
        "Animation",
        "Architecture",
        "Fashion Design",
        "Fine Art",
        "Game Design",
        "Graphic Design",
        "Identity Design",
        "Illustration",
        "Music",
        "Music Production",
        "Photography",
        "Product Design",
        "Typography",
        "UI/UX Design",
        "Videography",
        "Web Design",
        "Writing"
    ],
    "Computer Science": [
        "Blockchain",
        "Cybersecurity",
        "Data Science",
        "Databases",
        "E-Commerce",
        "Game Development",
        "Mobile App Development",
        "Web Development",
        "Artificial Intelligence"
    ],
    Business: [
        "Advertising",
        "Accounting",
        "Branding",
        "Business Law",
        "Cryptocurrency",
        "Data & Analytics",
        "Entrepreneurship",
        "Finance",
        "Growth Hacking",
        "Human Resources",
        "Management",
        "Marketing",
        "Productivity",
        "Public Relations",
        "Search Engine Optimization",
        "Social Media"
    ],
    Academics: [
        "Anthropology",
        "Archaeology",
        "Arts",
        "Astronomy",
        "Biology",
        "Chemistry",
        "Earth Science",
        "Economics",
        "Engineering",
        "Geography",
        "History",
        "Languages",
        "Law",
        "Mathematics",
        "Political Science",
        "Philosophy",
        "Physics",
        "Psychology",
        "Sociology",
        "Theology"
    ],
    Lifestyle: ["Cooking", "Wellness", "Personal Development"]
};

export const TIME_WATCHED = [
    {
        data: ["0-4", "10-32", "55"],
        dataTime: ["08-11-20", "09-11-20", "10-11-20"]
    },
    {
        data: ["0-10", "10-320", "550-600", "800-820"],
        dataTime: ["04-11-20", "10-11-20", "10-11-20", "11-11-20"]
    },
    {
        data: ["20-22", "100-243", "355-356"],
        dataTime: ["04-11-20", "11-11-20", "11-11-20"]
    },
    {
        data: ["30-34", "44-48", "550-700"],
        dataTime: ["05-11-20", "07-11-20", "10-11-20"]
    },
    {
        data: ["0-4", "5", "10"],
        dataTime: ["06-11-20", "08-11-20", "11-11-20"]
    },
    {
        data: ["500-1000", "2000-3000", "3200"],
        dataTime: ["09-11-20", "09-11-20", "09-11-20"]
    },
    {
        data: ["0-4", "10-33", "55-56"],
        dataTime: ["03-11-20", "05-11-20", "10-11-20"]
    }
];

export const ALL_LANGUAGES = [
    "Abkhazian",
    "Afar",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari languages",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan, Valencian",
    "Central Khmer",
    "Chamorro",
    "Chechen",
    "Chichewa, Chewa, Nyanja",
    "Chinese",
    "Church Slavonic, Old Bulgarian, Old Church Slavonic",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi, Dhivehi, Maldivian",
    "Dutch, Flemish",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fulah",
    "Gaelic, Scottish Gaelic",
    "Galician",
    "Ganda",
    "Georgian",
    "German",
    "Gikuyu, Kikuyu",
    "Greek (Modern)",
    "Greenlandic, Kalaallisut",
    "Guarani",
    "Gujarati",
    "Haitian, Haitian Creole",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Ido",
    "Igbo",
    "Indonesian",
    "Interlingua (International Auxiliary Language Association)",
    "Interlingue",
    "Inuktitut",
    "Inupiaq",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Kinyarwanda",
    "Komi",
    "Kongo",
    "Korean",
    "Kwanyama, Kuanyama",
    "Kurdish",
    "Kyrgyz",
    "Lao",
    "Latin",
    "Latvian",
    "Letzeburgesch, Luxembourgish",
    "Limburgish, Limburgan, Limburger",
    "Lingala",
    "Lithuanian",
    "Luba-Katanga",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Manx",
    "Maori",
    "Marathi",
    "Marshallese",
    "Moldovan, Moldavian, Romanian",
    "Mongolian",
    "Nauru",
    "Navajo, Navaho",
    "Northern Ndebele",
    "Ndonga",
    "Nepali",
    "Northern Sami",
    "Norwegian",
    "Norwegian Bokmål",
    "Norwegian Nynorsk",
    "Nuosu, Sichuan Yi",
    "Occitan (post 1500)",
    "Ojibwa",
    "Oriya",
    "Oromo",
    "Ossetian, Ossetic",
    "Pali",
    "Panjabi, Punjabi",
    "Pashto, Pushto",
    "Persian",
    "Polish",
    "Portuguese",
    "Quechua",
    "Romansh",
    "Rundi",
    "Russian",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Sardinian",
    "Serbian",
    "Shona",
    "Sindhi",
    "Sinhala, Sinhalese",
    "Slovak",
    "Slovenian",
    "Somali",
    "Sotho, Southern",
    "South Ndebele",
    "Spanish, Castilian",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tonga (Tonga Islands)",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Twi",
    "Uighur, Uyghur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volap_k",
    "Walloon",
    "Welsh",
    "Western Frisian",
    "Wolof",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang, Chuang",
    "Zulu"
];
